keyStore:
  supportedTypes: PKCS12, JKS

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: health, prometheus
      path-mapping:
        health: v2/health
        prometheus: v1/metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        # Define the order of severity. If one component is DOWN, the whole app is DOWN.
        # If one is DEGRADED and others are UP, the app is DEGRADED.
        order: DOWN, OUT_OF_SERVICE, DEGRADED, UP, UNKNOWN
        http-mapping:
          # Map custom status DEGRADED to HTTP 200 OK (or 503 if you prefer)
          DEGRADED: 200
          OUT_OF_SERVICE: 503
          DOWN: 503
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskSpace:
      enabled: false
    ping:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  flyway:
    out-of-order: true
    schemas: ${DB_SCHEMA:common_secret}
    table: common_secret_schema_history
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:common_secret}
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

server:
  port: ${PORT:8080}
  error:
    include-message: ${INCLUDE_ERROR:always}
